const data = {
  abin: {
    fname: "abin",
    lname: "joseph",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  anju: {
    fname: "anju",
    lname: "gopan",
    dept: "CSE",
    NumberOfPhotos: 2,
  },
  poojalakshmi: {
    fname: "poojalakshmi",
    lname: "pk",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  haripriya: {
    fname: "haripriya",
    lname: "ks",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  pooja: {
    fname: "pooja",
    lname: "mp",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  athira: {
    fname: "athira",
    lname: "menon",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  jeethu: {
    fname: "jeethu",
    lname: "joshy",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },

  kashish: {
    fname: "kashish",
    lname: "s shah",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  riswana: {
    fname: "Riswana",
    lname: "E A",
    dept: "computer science and engineering",
    NumberOfPhotos: 2,
  },
  thaniya: {
    fname: "thaniya",
    lname: "azhar",
    dept: "vidyodaya",
    NumberOfPhotos: 2,
  },
  ashigha: {
    fname: "Maria",
    lname: "Ashigha",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },

  farzana: {
    fname: "Farzana",
    lname: "Khareem",
    dept: "Computer Science",
    NumberOfPhotos: 2,
  },
  roushath: {
    fname: " Roushath",
    lname: " Beevi K S",
    dept: " CSE",
    NumberOfphotos: 2,
  },
  rizwan: {
    fname: "Rizwan",
    lname: " K Rahim",
    dept: "CSE",
    NumberOfPhotos: 2,
  },
  suroor: {
    fname: "M S",
    lname: "Mohammed",
    dept: "Industrial Instrumentation and Automation",
    NumberOfPhotos: 2,
  },
  sabreen: {
    fname: "Sabreen Rafeek",
    lname: "Sabreen",
    dept: "Mechanical",
    NumberOfPhotos: 2,
  },
  beegum: {
    fname: "Fathima",
    lname: "Beegum PJ",
    dept: "Alumni",
    NumberOfPhotos: 2,
  },
  pooja: {
    fname: "pooja",
    lname: "mp",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  shebeeb: {
    fname: "Muhammed",
    lname: "Shebeeb K M",
    dept: "Electrical and Electronics Engineering",
    NumberOfPhotos: 2,
  },
  abin: {
    fname: "abin",
    lname: "joseph",
    dept: "Computer science and engineering",
    NumberOfPhotos: 2,
  },
  varun: {
    fname: "Varun",
    lname: "Madhu",
    dept: "Mechanical",
    NumberOfPhotos: 1,
  },
  mansoor: {
    fname: "mansoor",
    lname: "majeed",
    dept: "computer science and engineering",
    NumberOfPhotos: 2,
  },
  nujoom: {
    fname: "Nujoom",
    lname: "Rahman",
    dept: "Mechanical",
    NumberOfPhotos: 1,
  },
  ashique: {
    fname: "Ashique",
    lname: "Sherief",
    dept: "Computer",
    NumberOfPhotos: 3,
  },
  imrosh: {
    fname: "K M Muhammed",
    lname: "Imrosh",
    dept: "Mechanical",
    NumberOfPhotos: 3,
  },
  akash: {
    fname: "Akash",
    lname: "Santhosh",
    dept: "IT",
    NumberOfPhotos: 2,
  },
};
export default data;
